name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repository files
        run: ls -la
      - name: Validate Markdown (optional)
        run: |
          if command -v markdownlint >/dev/null 2>&1; then
            markdownlint **/*.md || true
          else
            echo "markdownlint not installed; skipping"
          fi
